services:
  api:
    stdin_open: true
    tty: true
    build: .
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml
    ports:
      - 8000:8000
    command: |
      uv run /app/divvywonga/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./divvywonga:/app/divvywonga
      - db_data:/app/data

volumes:
  db_data:
