# Generated by Django 5.2.4 on 2026-04-06 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_alter_membership_role_tournament_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("football", "Football"),
                            ("basketball", "Basketball"),
                            ("tennis", "Tennis"),
                            ("baseball", "Baseball"),
                            ("hockey", "Hockey"),
                            ("other", "Other"),
                        ],
                        default="football",
                        max_length=20,
                    ),
                ),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("league", "League"),
                            ("knockout", "Knockout"),
                            ("round_robin", "Round Robin"),
                            ("mixed", "Mixed Format"),
                        ],
                        default="league",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="users.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "ordering": ["-created_at"],
                "unique_together": {("name", "group")},
            },
        ),
        migrations.CreateModel(
            name="TournamentParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        help_text="Points earned by the user in this specific tournament",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                            ("predictor", "Predictor"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.group"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Participation",
                "verbose_name_plural": "Tournament Participations",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "tournament")},
            },
        ),
    ]
